language: php
php:
  - 5.6
  - 5.5
  - '7'
  - hhvm
before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
script:
  - composer test
after_script:
  - composer coveralls
after_success:
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi
matrix:
  fast_finish: true
sudo: false
notifications:
  email: false
